# Generated by Django 4.2 on 2023-07-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nama_produk',
            new_name='name',
        ),
    ]
